### ISSUE TITLE
app launching forever

### ISSUE THREAD

**Issue by juritobi** [vitrine-app/vitrine#126]
I'm using windows I have just installed it but when I run it says looking for updates and then starts launching for ever.

I don't know if this will be of any help, but if I run the app again after closing it with alt+f4 or while still opened it opens a window with just a grey background.

I would really like to test and use the app, is there anything I should try to make it work on my side or shuold I just wait for a fix?

**Comment by paul-roman** [comment]
Thank you very much for your feedback! The bug is been already found in #121, a fix is already done and is on its way to production ;)
Still, il you want to test the app, you can manually solve it by going to `AppData\Roaming\vitrine\data\config\vitrine_config.json` and modify it by adding `{}` inside or `{ "lang": "en" }`.
That should work!

**Comment by paul-roman** [comment]
Don't worry, that's a great job you're doing by giving me feedbacks, I really appreciate it! Most of the bugs are indeed known, can you please give your logs? You can find them at `AppData\Roaming\vitrine\data\vitrine.log.html`

**Comment by juritobi** [comment]
here are the logs for the issues I'v gathered

adding game form steam:
![adding game from steam](https://user-images.githubusercontent.com/36984751/51637048-06ea1580-1f5b-11e9-80c4-c1199f265e69.PNG)

activating search non installed games in steam:
![activating search non intalled games in steam](https://user-images.githubusercontent.com/36984751/51637050-06ea1580-1f5b-11e9-9bc0-813e44f95515.PNG)
sadly, looking at the log it doesn't seem that its just taking long to load all the games :(

inserting invalid path:
![inserting invalid path](https://user-images.githubusercontent.com/36984751/51637051-0782ac00-1f5b-11e9-8fa4-e65b7b72f325.PNG)
I tried this because I have steam installed on C: but I usually install all the games on D: where I have space but the app is not detecting the games I have installed in D: 
I think it's something that should be addressed at some point

clicking add all button
![clicking add all button](https://user-images.githubusercontent.com/36984751/51637052-0782ac00-1f5b-11e9-884c-15e1122c55bb.PNG)

filling details:
![filling details](https://user-images.githubusercontent.com/36984751/51637053-0782ac00-1f5b-11e9-8595-0eb48efdbe25.PNG)

**Comment by paul-roman** [comment]
Thank you very much! I'll try my best to do some fixes when I find the time to 😉

**Comment by paul-roman** [comment]
The production bug about forever launch had just got into production!
Sorry it took so long I was kinda busy, I'm now working on the other bugs
